import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/about.module.css";
import { useContext } from "react";
import { NotificationContext } from "../contexts/NotificationContext";
import SendEmail from "../components/SendEmail";
import Footer from "../components/Footer";

const Author: NextPage = () => {
  const { notification } = useContext(NotificationContext);

  return (
    <div>
      <Head>
        <title>The author | Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header openProjects={() => {}} />
      <main className={`${styles.mainContent} centerContainer`}>
        <section className={styles.contentBlock}>
          <img
            className={styles.profilePicture}
            src="https://media.licdn.com/dms/image/D4D03AQGyl6E65N0tMA/profile-displayphoto-shrink_200_200/0/1675489841490?e=1680739200&v=beta&t=SiXPiGfXv_2qh2ALoWYWomztCw25f_0pFjFmYsx1kA8"
            alt=""
          />
          <div className={styles.textBlock}>
            <h2>The author</h2>
            <p>
              Hi there. I&apos;m Fenil Narola, a <b>web developer</b>. Nowdays,
              I&apos;m in my journey to became a <b>Fullstack Web Developer</b>,
              and this project is a part of it. You may view further projects in
              my{" "}
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://linef-portfolio.netlify.app"
              >
                Portfolio
              </a>
              . I created this project based on a youtube video and it was also
              my introduction to React and Next.JS. I also own blog site{" "}
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://linefblog.com"
              >
                Linef
              </a>
              .
            </p>
          </div>
        </section>

        <section className={styles.contentBlock}>
          <div className={styles.textBlock}>
            <h2>With this project</h2>
            <p>
              It was created as a <b>learning project</b>, to improve my
              knowledge and skills. Checking and test the new features of
              Next.js 12 framework and I&apos;ve tried some tutorial to learn
              from basics.
            </p>
          </div>
          <img
            src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_developer_activity_bv83_CHQjsEGXJ.svg?updatedAt=1636637987039"
            alt=""
          />
        </section>

        <section className={styles.contentRow}>
          <h2>Get in touch with me</h2>
          <div className={styles.contentBlock}>
            <div className={styles.socialLinks}>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://www.youtube.com/channel/UCUT0OqjYseS7GKsOQdouGYg"
              >
                <img
                  className={`${styles.socialItem} ${styles.linkYoutube}`}
                  src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_youtube_icon_KQ3Mu29f9Vjv.svg?updatedAt=1636635922070"
                />
              </a>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://www.linkedin.com/in/fenil-narola-813ab2211"
              >
                <img
                  className={`${styles.socialItem} ${styles.linkLinkedin}`}
                  src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_linkedin_icon_qW0U6Df8q.svg?updatedAt=1636635922444"
                />
              </a>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://github.com/Fenil-Narola"
                className={`${styles.socialItem} ${styles.linkGithub}`}
              >
                <img src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_github_icon_Df3Xanhbpl.svg?updatedAt=1636635922146" />
              </a>
              <img
                src="https://ik.imagekit.io/lrjseyuxi3m/todoapp/undraw_social_ideas_re_j5v4_8fl8yGcsFLY.svg?updatedAt=1636637986700"
                alt=""
              />
            </div>
            <div className={styles.textBlock}>
              <SendEmail />
            </div>
          </div>
        </section>
      </main>
      <Footer />
      {notification}
    </div>
  );
};

export default Author;
